### PR TITLE
[PP-SIDNEY] Postgres instance configuration added

### PR DESCRIPTION
**Pull request by sidneymiranda**
Docker-compose configuration file added, please review.

### CODE REVIEW

**Comment by 4lexRossi** [comment]
You are requesting merge into master but the correct one is the develop, change that clicking in edit then in the branch and then choose the develop one

**Comment by sidneymiranda** [comment]
Done.

**Comment by 4lexRossi** [comment]
Your branch has conflicts to resolve first, what i suggest you is execute these commands first
1. On your branch type "git fetch" so the update branchs will be fetched in your local machine
2. type "git rebase origin/develop" to do the rebase locally, at this moment will problably appear the conflicts, and you should resolve then first and then save
3. after that you type "git rebase --continue" to or finish or go to the next conflict, if do that repeat step number 2 until go to the option one on this topic
4. resoveld all the conflicts you publish your branch again with "git push origin PP-SIDNEY" but u gonna have to add a "-f" flag at the end so the full command will be "git push origin PP-SIDNEY -f"

**Comment by sidneymiranda** [comment]
All conflicts have been resolved.

**Pull request merged**
